FROM node:24-alpine

WORKDIR /app

ENV CHOKIDAR_USEPOLLING=true

RUN apk add --no-cache docker-cli

COPY package.json ./
COPY prisma.config.ts ./
COPY docker/entrypoint.dev.sh ./

RUN npm i --ignore-scripts
RUN sed -i 's/\r$//' /app/entrypoint.dev.sh
RUN chmod +x /app/entrypoint.dev.sh

EXPOSE 5173

ENTRYPOINT ["sh", "/app/entrypoint.dev.sh"]
# wait command
# CMD ["tail", "-f", "/dev/null"]
