
<?php

//! +------------------------------+
//! | SECURE FILE								   |
//! +------------------------------+

/**
 * Please DO NOT edit this file manually to prevent bugs.
 * If you want to change the content, please modify your EML AdminTool configuration or reset it.
 */


$config = [
	'db' => [
		'host' => '',
		'name' => '',
		'username' => '',
		'password' => ''
	],
	'info' => [
		'lang' => '',
		'server_id' => '',
		'server_name' => '',
		'server_password' => '',
		'end_config' => false
	]
];